### ISSUE TITLE
Show the list of people in Company page

### ISSUE THREAD

**Issue by smaffulli** [VizGrimoire/VizGrimoireJS#61]
Pages like http://activity.openstack.org/dash/browser/company.html?company=Yahoo!&release=kilo would benefit from showing the individual list of people affiliated to it, not just the total count.

**Comment by dicortazar** [comment]
Hi, this already contains the list of people.

There are missing tables from code review, but those are in progress.

Closing this, thanks for your comments! :).

ps: please, feel free to reopen the ticket if you feel this is not what you expected.
