### ISSUE TITLE
Error when pointing to data/metrics.json instead of browser/data/metrics.json

### ISSUE THREAD

**Issue by dicortazar** [VizGrimoire/VizGrimoireJS#62]
According to https://phabricator.wikimedia.org/T104176, the ~/data/metrics.json is needed to show specific metrics in the http://korma.wmflabs.org/browser/gerrit_review_queue.html panel.

I've updated the ~/browser/data/metrics.json file and added a link from ~/data/ to ~/browser/data in https://github.com/Bitergia/mediawiki-dashboard/commit/abe692cbe3f6ad1036bed523bc6b608871720660

If we're not using anymore the ~/data/ directory, we should change the specific JS and HTML to point to the other place.

**Comment by dicortazar** [comment]
As far as I know, the error was introduced in https://github.com/Bitergia/mediawiki-dashboard/commit/dc90db5b7a18f9aae6a8a7ff4fddda4c7b034875

**Comment by sanacl** [comment]
This is fixed in master version.
